import type { ThemeDefinition } from "./types";

export const draculaTheme: ThemeDefinition = {
  id: "dracula",
  name: "Dracula",
  palettes: {
    light: {
      canvas: "#DEDCCF",
      surface: "#CECCC0",
      surfaceAlt: "#BCBAB3",
      hover: "#ECE9DF",
      text: "#1F1F1F",
      textMuted: "#3d362a",
      textInverse: "#DEDCCF",
      border: "#CECCC0",
      borderStrong: "#BCBAB3",
      accent: "#036A96",
      accentHover: "#644AC9",
      accentSubtle: "#ECE9DF",
      focus: "#815CD6",
      positive: "#14710A",
      negative: "#CB3A2A",
      energyLowBg: "#ECE9DF",
      energyLowAccent: "#14710A",
      energyLowText: "#1F1F1F",
      energyMediumBg: "#ECE9DF",
      energyMediumAccent: "#036A96",
      energyMediumText: "#1F1F1F",
      energyHighBg: "#ECE9DF",
      energyHighAccent: "#644AC9",
      energyHighText: "#1F1F1F",
    },
    dark: {
      canvas: "#191A21",
      surface: "#21222C",
      surfaceAlt: "#343746",
      hover: "#424450",
      text: "#F8F8F2",
      textMuted: "#a0acd8",
      textInverse: "#191A21",
      border: "#282A36",
      borderStrong: "#424450",
      accent: "#8BE9FD",
      accentHover: "#BD93F9",
      accentSubtle: "#343746",
      focus: "#815CD6",
      positive: "#50FA7B",
      negative: "#FF5555",
      energyLowBg: "#343746",
      energyLowAccent: "#50FA7B",
      energyLowText: "#F8F8F2",
      energyMediumBg: "#343746",
      energyMediumAccent: "#8BE9FD",
      energyMediumText: "#F8F8F2",
      energyHighBg: "#343746",
      energyHighAccent: "#BD93F9",
      energyHighText: "#F8F8F2",
    },
  },
};
