import type { ThemeDefinition } from "./types";

export const everforestTheme: ThemeDefinition = {
  id: "everforest",
  name: "Everforest",
  palettes: {
    light: {
      canvas: "#FDF6E3",
      surface: "#F4F0D9",
      surfaceAlt: "#EFEBD4",
      hover: "#E6E2CC",
      text: "#5C6A72",
      textMuted: "#5C6A72",
      textInverse: "#FDF6E3",
      border: "#BDC3AF",
      borderStrong: "#A6B0A0",
      accent: "#3A94C5",
      accentHover: "#2E7BA8",
      accentSubtle: "#EFEBD4",
      focus: "#3A94C5",
      positive: "#8DA101",
      negative: "#F85552",
      energyLowBg: "#F0F1D2",
      energyLowAccent: "#6e7e00",
      energyLowText: "#5C6A72",
      energyMediumBg: "#E9F0E9",
      energyMediumAccent: "#3285b5",
      energyMediumText: "#5C6A72",
      energyHighBg: "#FAE8E2",
      energyHighAccent: "#c84fa3",
      energyHighText: "#5C6A72",
    },
    dark: {
      canvas: "#2D353B",
      surface: "#343F44",
      surfaceAlt: "#3D484D",
      hover: "#475258",
      text: "#D3C6AA",
      textMuted: "#b2beb5",
      textInverse: "#2D353B",
      border: "#4F585E",
      borderStrong: "#56635F",
      accent: "#7FBBB3",
      accentHover: "#6AA8A0",
      accentSubtle: "#3D484D",
      focus: "#7FBBB3",
      positive: "#A7C080",
      negative: "#E67E80",
      energyLowBg: "#425047",
      energyLowAccent: "#A7C080",
      energyLowText: "#D3C6AA",
      energyMediumBg: "#3A515D",
      energyMediumAccent: "#7FBBB3",
      energyMediumText: "#D3C6AA",
      energyHighBg: "#4A444E",
      energyHighAccent: "#D699B6",
      energyHighText: "#D3C6AA",
    },
  },
};
