import type { ThemeDefinition } from "./types";

export const nordTheme: ThemeDefinition = {
  id: "nord",
  name: "Nord",
  palettes: {
    light: {
      canvas: "#ECEFF4",
      surface: "#E5E9F0",
      surfaceAlt: "#D8DEE9",
      hover: "#E5E9F0",
      text: "#2E3440",
      textMuted: "#4C566A",
      textInverse: "#ECEFF4",
      border: "#81A1C1",
      borderStrong: "#5E81AC",
      accent: "#5E81AC",
      accentHover: "#5E81AC",
      accentSubtle: "#D8DEE9",
      focus: "#4C566A",
      positive: "#A3BE8C",
      negative: "#BF616A",
      energyLowBg: "#D8E7D4",
      energyLowAccent: "#4d7a3e",
      energyLowText: "#2E3440",
      energyMediumBg: "#D4E3EC",
      energyMediumAccent: "#5E81AC",
      energyMediumText: "#2E3440",
      energyHighBg: "#DFD5E8",
      energyHighAccent: "#8a6990",
      energyHighText: "#2E3440",
    },
    dark: {
      canvas: "#2E3440",
      surface: "#3B4252",
      surfaceAlt: "#434C5E",
      hover: "#3B4252",
      text: "#ECEFF4",
      textMuted: "#D8DEE9",
      textInverse: "#2E3440",
      border: "#4C566A",
      borderStrong: "#81A1C1",
      accent: "#88C0D0",
      accentHover: "#81A1C1",
      accentSubtle: "#434C5E",
      focus: "#8FBCBB",
      positive: "#A3BE8C",
      negative: "#BF616A",
      energyLowBg: "#3A4A43",
      energyLowAccent: "#A3BE8C",
      energyLowText: "#ECEFF4",
      energyMediumBg: "#3A4A5C",
      energyMediumAccent: "#81A1C1",
      energyMediumText: "#ECEFF4",
      energyHighBg: "#4B4258",
      energyHighAccent: "#B48EAD",
      energyHighText: "#ECEFF4",
    },
  },
};
