import type { ThemeDefinition } from "./types";

export const rewardsNexusTheme: ThemeDefinition = {
  id: "rewards-nexus",
  name: "Rewards Nexus",
  palettes: {
    light: {
      canvas: "#eef4ff",
      surface: "#fbfdff",
      surfaceAlt: "#e5edff",
      hover: "#d8e5ff",
      text: "#101b3d",
      textMuted: "#53618a",
      textInverse: "#ffffff",
      border: "#bfd0f5",
      borderStrong: "#7d98d6",
      accent: "#3559e8",
      accentHover: "#2441bd",
      accentSubtle: "#dce5ff",
      focus: "#7a47f5",
      positive: "#008f72",
      negative: "#d93669",
      energyLowBg: "#d9f7f3",
      energyLowAccent: "#00a99a",
      energyLowText: "#00655d",
      energyMediumBg: "#e8e2ff",
      energyMediumAccent: "#7957ea",
      energyMediumText: "#49309c",
      energyHighBg: "#fff0c9",
      energyHighAccent: "#e38b00",
      energyHighText: "#7b4800",
    },
    dark: {
      canvas: "#02040d",
      surface: "#080e20",
      surfaceAlt: "#0e1730",
      hover: "#18264a",
      text: "#edf4ff",
      textMuted: "#91a4ce",
      textInverse: "#050917",
      border: "#22376a",
      borderStrong: "#3857a0",
      accent: "#55c7ff",
      accentHover: "#91dcff",
      accentSubtle: "#102950",
      focus: "#a66cff",
      positive: "#4fe2b4",
      negative: "#ff648c",
      energyLowBg: "#082a2d",
      energyLowAccent: "#2ee6d1",
      energyLowText: "#a3fff4",
      energyMediumBg: "#201b4e",
      energyMediumAccent: "#9a7bff",
      energyMediumText: "#ddd3ff",
      energyHighBg: "#3b2608",
      energyHighAccent: "#ffbe3d",
      energyHighText: "#ffe4a0",
    },
  },
};
