import type { ThemeDefinition } from "./types";

export const tokyoNightTheme: ThemeDefinition = {
  id: "tokyo-night",
  name: "Tokyo Night",
  palettes: {
    light: {
      canvas: "#e6e7ed",
      surface: "#dee0e6",
      surfaceAlt: "#d6d8df",
      hover: "#c6c9d1",
      text: "#363c4d",
      textMuted: "#595e71",
      textInverse: "#e6e7ed",
      border: "#c1c2c7",
      borderStrong: "#9da0ab",
      accent: "#2959aa",
      accentHover: "#1d4a8a",
      accentSubtle: "#d8dfee",
      focus: "#0f7c90",
      positive: "#2d7b74",
      negative: "#bd4040",
      energyLowBg: "#d3e8e5",
      energyLowAccent: "#2d7b74",
      energyLowText: "#1a4f4a",
      energyMediumBg: "#d8dfee",
      energyMediumAccent: "#2959aa",
      energyMediumText: "#1a3470",
      energyHighBg: "#dfdaec",
      energyHighAccent: "#5a3e8e",
      energyHighText: "#3b1f6a",
    },
    dark: {
      canvas: "#1a1b26",
      surface: "#1c1d2a",
      surfaceAlt: "#1e202e",
      hover: "#232433",
      text: "#a9b1d6",
      textMuted: "#8589a8",
      textInverse: "#1a1b26",
      border: "#2a2d40",
      borderStrong: "#363b54",
      accent: "#7aa2f7",
      accentHover: "#6183bb",
      accentSubtle: "#1e202e",
      focus: "#7dcfff",
      positive: "#9ece6a",
      negative: "#f7768e",
      energyLowBg: "#1a2018",
      energyLowAccent: "#9ece6a",
      energyLowText: "#c5e0b8",
      energyMediumBg: "#1a1d2e",
      energyMediumAccent: "#7aa2f7",
      energyMediumText: "#b3c6ea",
      energyHighBg: "#1e1b2e",
      energyHighAccent: "#bb9af7",
      energyHighText: "#d0bff0",
    },
  },
};
